### ISSUE TITLE
repeated tasks not working

### ISSUE THREAD

**Issue by wackoamd1** [hexparrot/mineos-node#109]
im running mineos on freenas.
i want to run a restore point every 45 minutes between 11am and 2am
so my cronjob looks like:  */45 11-2 * * *
it runs at 11am but not every 45 minutes after that.

my backup task works flawless ( 0 */2 * * *) it backs up every 2 hour.

it just looks like the same formula doesn't work for minutes . is this a bug

**Comment by hexparrot** [comment]
Does the log show the attempt to restore?  Or are you just not seeing the backtracking in the in-game world?

**Comment by hexparrot** [comment]
So there are two issues at hand.

The first and foremost problem it turns out is that cronjob hours work on 24 hour time.  So `11-2` actually registered as 1, 2, 11, 12.  Your intended behavior, however, would require `11-14`.

The second problem is that `*/45` only works on a single-hour basis.  So I don't believe it's possible to do a rolling 'every 45 minutes'.  Customary `/` values are usually in nice, even divisors of 60, such as `*/15` or `*/30`.  `*/45`, on the other hand, only does minute 0 and minute 45, of each of the hours.
