### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by cowchmonkey** [hexparrot/mineos-node#126]
first trying to cahnge https to false. wont take
second trying to change backup and archive dir as i dont want to fill up my ssd with backups 
but wont take 
i change the config file in /usr/games/minecraft restarted mineos and even my hole server and still nothing everything is still default

**Comment by hexparrot** [comment]
Just confirming: you are using MineOS node, correct?  Not the python webui?

This config does not have a way to change the MineOS directories around, so any attributes for that purpose will have no effect. 

If you wish to have any of your MineOS directories elsewhere, the cleanest way to do it is to remove/move your directory to the desired path. Following that, create a symlink from the old, expected location within /var/games/minecraft to your new, desired path.

**Comment by cowchmonkey** [comment]
Yup it's the node version and thank you all do that. With the symlink still new to Linux so don't no all the tricks yet.

**Comment by hexparrot** [comment]
Are you changing /etc/mineos.conf or /usr/games/minecraft/mineos.conf?

**Comment by cowchmonkey** [comment]
/usr/games/minecraft/mineos.conf

**Comment by hexparrot** [comment]
When relocating any of the MineOS directories, you can follow steps like these:

```
root@willonubuntu:~# cd /var/games/minecraft/
root@willonubuntu:/var/games/minecraft# ls
archive  backup  import  profiles  servers
root@willonubuntu:/var/games/minecraft# mv archive /root/archive
root@willonubuntu:/var/games/minecraft# ln -s /root/archive .
root@willonubuntu:/var/games/minecraft# ls -la
total 24
drwxr-xr-x 6 root root 4096 Sep 21 13:18 .
drwxr-xr-x 3 root root 4096 Sep 21 13:15 ..
lrwxrwxrwx 1 root root   13 Sep 21 13:18 archive -> /root/archive
drwxrwxr-x 2 root root 4096 Sep 21 13:15 backup
drwxrwxrwx 2 root root 4096 Sep 21 13:15 import
drwxrwxr-x 2 root root 4096 Sep 21 13:15 profiles
drwxrwxr-x 2 root root 4096 Sep 21 13:15 servers
```

MineOS will still save to /var/games/minecraft/archive.  But the filesystem itself will make sure the files get saved where you want it (in this example, /root/archive), so MineOS never needs to know better.

**Comment by cowchmonkey** [comment]
also i dont have a /etc/mineos.conf

**Comment by hexparrot** [comment]
There's the problem then; the instructions have the mineos.conf file relocated to /etc/mineos.conf.  If you missed that step/didn't do it/didn't know about it, just know that configuration in Linux usually ends up in /etc/, and that's where the webui actually looks.  The copy that exists in /usr/games/minecraft is not used in any way; it's just there because that's how it gets onto the filesystem in the first place (via git)

**Comment by cowchmonkey** [comment]
yes i apt-get installed it ontop of my ubuntu server

**Comment by cowchmonkey** [comment]
well the https issue yes but all i want is to move the archive and backup folder to a diff dir the server and profile can stay on the ssd but in the config theres only "base_directory" so unless theres a way to say archive dir = something then all have to do a symlink like u said earlier

**Comment by cowchmonkey** [comment]
but i did move this file already

**Comment by hexparrot** [comment]
Do you have any unanswered questions at this point?

The mineos.conf addresses the HTTPS->HTTP issue. I don't recommend doing this, by the way.  You'll be sending your Linux usernames and passwords in cleartext.

The symlink addresses moving any of the 5 directories (archive, backup) to another location of your choosing.

**Comment by cowchmonkey** [comment]
ok on he https and no i think u answered everything, im just messing with the symlink now trying to get it to work its not showing up like u had in  ur example above

**Comment by hexparrot** [comment]
If you provide the commands you're typing in (or can describe where you intend for your dirs to be moved), I can help you construct/debug whatever issue is still cropping up.

**Comment by cowchmonkey** [comment]
lol well what ever i did i really broke it all have to reinstall something but i have a few friends on and dont really want to kick them off lol. anyways what i was mainly trying to do is symlink archive and backup to "/media/share/minecraft" however thats on a diff drive and it was giving me "mv: inter-device move failed: ‘archive’ to ‘/media/share/minecraft/archive’; unable to remove target:"

**Comment by flareofghast** [comment]
You'll have to stop mineos to move them.

**Comment by hexparrot** [comment]
I'm not sure he should *have* to, as /backup and /archives don't really get interacted with, short of cronjobs and deliberate backups/archives.  I think that the issue might be something else.

Instead of mving, trying copying (cp).  It might be related to what you're seeing in this article, and that you're going across entire physical devices: http://insanelabs.com/linux/linux-cannot-move-folders-inter-device-move-failed-unable-to-remove-target-is-a-directory/

**Comment by cowchmonkey** [comment]
ok so i got it all to work ty for the patients with me youll get a good laugh though the hole time i was getting mad i was doing ls -s and i should have been ln -s, fat fingures

**Comment by cowchmonkey** [comment]
well i got the symlink to work but its not seeing the profiles when i download a new server

**Comment by hexparrot** [comment]
Try refreshing your browser--does that make them reappear?  You didn't move the profiles dir, correct?

**Comment by cowchmonkey** [comment]
ok all is well now all symlinks work and servers start up and i can see everything thanks again and keep up the great work

**Comment by flareofghast** [comment]
I assumed you had a watch on the directories.

**Comment by hexparrot** [comment]
There's a watch on /archives and /servers, but not /backup.  That said, the watch doesn't lock down the files in any way, so it shouldn't impede filesystem actions.  As an example, a live server directory is watched, even as it is deleted from the webui; it just stops getting watched.  None of the files should be opened/locked by the watch, so that's why a move of the whole directory should be possible.
