### ISSUE TITLE
Log in failure redirects you to the old login page

### ISSUE THREAD

**Issue by yesiateyoursheep** [hexparrot/mineos-node#132]
If I enter a wrong password, I get redirected to /auth, which doesn't exist.

**Comment by MrBretze** [comment]
I confirm this bug

**Comment by hexparrot** [comment]
Can't reproduce on current commit.  What commit are you on?

**Comment by yesiateyoursheep** [comment]
The webui isn't displaying a commit version, but whatever the latest commit was as of the 1st of October.
I'll add some more details, the webui is running on a fresh install of Debian Jessie 64 bit with no desktop environment, and only the dependencies for mineos installed on top. Note that I was unable to install openjdk 7, so I installed Oracle Java 7 JDE instead.

**Comment by MrBretze** [comment]
I tested the same build on ubuntu and it work, please fix this for Fedora :/

**Comment by MrBretze** [comment]
Building failure: http://puu.sh/ky8Id/8d071fee77.png

**Comment by hexparrot** [comment]
I have pinned this issue down to incompatibilities between Node v4 (stable) and earlier versions, such as 0.12.x.

Recent commits have made it so that MineOS works well on the stable Node v4, but it appears these dependency changes also break it for previous versions.

Long story short: best if you update your node to 4.x+, but if you can't, you just need to roll back your repo a few commits to use the older dependencies.

See the following page for the resolution:

https://github.com/hexparrot/mineos-node/issues/134
