### ISSUE TITLE
Mineos broken

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#134]
I cant install mineos on Debian 8, Ubuntu 14.04, Fedora 22/21/20, centos 7 and 6.5 It's the same error for all (http://puu.sh/kym9Z/c393e63dba.png)

**Comment by hexparrot** [comment]
Your issue is the same as the one listed here:  http://discourse.codeemo.com/t/unable-to-update-install/833

It looks like you're using a version of node that is older than the current "stable" 4.x.  Node v4 is relatively recent in release, but the wiki has been updated to reflect this new, preferred version.

**If you're using a version of node earlier than 4.0, such as 0.12.x**:

    git fetch
    git checkout tags/v.1.0.1
    npm install

 **If you're using a version of node 4.0+**:

    git fetch
    git reset --hard origin/master
    npm install
