### ISSUE TITLE
Doesn't install FTB Modpacks Properly

### ISSUE THREAD

**Issue by firecrafty** [hexparrot/mineos-node#135]
I tried to install the Direwolf20 modpack through the web gui -created a server with the profile, accepted the eula, etc. But when I try to start it just doesn't start, no logs, no error messages, nothing. So I log in to my server through ssh and execute ServerStart.sh, it says that the required files need to be installed and it installs them. From there it worked fine from the web gui.

**Comment by hexparrot** [comment]
Currently, the webui does *not* have the code to run external shell scripts.  Most modpacks work simply with *just* the jar, though there are a few exceptions, with your DW20 being one of them.

I'll have to continue exploring a way in the webui to present **required shell scripts** to the user, so that they may run it, but it's been difficult to also try to filter out the shell scripts that often are included with modpacks that should *not* be run.  One example is that many modpacks have shell scripts that start the server for you, which would not work with MineOS, as MineOS starts the server with screen so it can be interacted with.

**Comment by yesiateyoursheep** [comment]
Perhaps, when installing a profile that has a chance of needing manual installation, like FTB modpacks, after creating a server with said profile has completed, make an interactive modal appear with a list of the contents of the server's folder, so that the user could select and interact with an installer shell script using something like the console system you have in the logs section. (Maybe this could be developed into a more useful feature, an in-modal file browser for uploading, viewing and deleting files, like logs, mods and editing config files out of mineos' reach.)

I think the alternative would either be by scanning the contents of all .sh files in a server for certain keywords that indicate that this needs to be run and doing so (but you would still need user interaction for some installers), or to create a database of custom scripts to run after installing certain profiles. - Both of which I imagine would be quite a bit more work.

**Comment by KiloJuliet** [comment]
If someone decided to get a load of md5sums and common names of various scripts generally used would we be able to create a menu that displayed only known-valid setup scripts? And maybe after running them we would have them automatically delete.

This would solve a huge problem of users running potentially bad/mallicious code.

I'd also note that many of these scripts I've found have various requirements such as curl, wget, and those would generally be fine, but a few setup scripts or setup jars I've seen (on ATLauncher packs so far) actually try to get you to open a browser window to download things through ad walls or pay/delay walls and in my opinion adwall/paywall services just should not be supported by the installer because it's just entirely too much work.

**Comment by hexparrot** [comment]
> If someone decided to get a load of md5sums and common names of various scripts generally used would we be able to create a menu that displayed only known-valid setup scripts? And maybe after running them we would have them automatically delete.

Problem is people aren't very good at keeping their webui up to date, so very often a script md5sum may not match and they'll get a false-negative that the script doesn't match any known md5sums.  This could potentially cause a UX issue...confusion, frustration, etc.  It could be as small as the script updating a comment or a file version and I'm afraid it'll do more harm than good.

Anyway, I believe it's less about bad/malicious code than it is incompatible code--where the script is meant to be run on its own, but that's not how MineOS expects to run it...nor can it recognize it via a non-`screen` approach.
