### ISSUE TITLE
Mine OS crashes when i create a server

### ISSUE THREAD

**Issue by davewanders** [hexparrot/mineos-node#149]
Error log: http://pastebin.com/kvMeP8a4
git commit: 036abe2

**Comment by hexparrot** [comment]
This might be caused by an old `node` version.  You appear to have 0.10.x, while the stable 4.x has already been released (and is what all testing is done on).

As best as I can tell, the error "Error: Cannot find module 'bytes'" should be resolved with a newer version.

So you can try the following things first:

    npm cache clean
    npm install

And try it again.  If it doesn't work, 4.x might be the next best thing to do (actually going to 4.x+ is probably the best thing anyway).

**Comment by hexparrot** [comment]
#150

**Comment by hexparrot** [comment]
What did you do that fixed it?
