### ISSUE TITLE
Output From BuildTools.Jar

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#155]
Change console type to minecraft console ?

this: http://puu.sh/lU7QI/3dbb695e09.png to this http://puu.sh/lU7Si/2ca17e4d35.png

**Comment by hexparrot** [comment]
Addressed in 4651eabece6c2f2235a276e3655aa22fb09c3196

Thanks for the suggestion.

Keep in mind, since all the logs are now kept in the webpage and scrollable, WHEN YOU BUILD craftbukkit/spigot, your client's webbrowser will slowly use more and more memory.  You can reclaim this memory by refreshing your browser.  This has no performance impact on the MineOS server itself.
