### ISSUE TITLE
MineOS as a docker container?

### ISSUE THREAD

**Issue by hobbes1069** [hexparrot/mineos-node#163]
I'm not sure how to mark this as an enhancement request...

But just an idea that would help solve a lot of the nodejs version or other dependency issues would be to setup MineOS in a docker container which can be set to start on boot just like a service.

**Comment by hexparrot** [comment]
Yes, a docker container would actually be quite nice, especially with the [Dockerfile already included](https://github.com/hexparrot/mineos-node/blob/master/Dockerfile) in the repo.

Right now at the current level of mineos-node's development and maturity, I'd agree it's a good time to figure out the process and document it as an official way to distribute and deploy...but I'm not so great at docker, so it's been being put off (in my own priorities).  If you know docker a bit better and can help with the broad strokes of getting it up and running cleanly, I'd happily polish off the instructions and make them official on the website and perhaps even a video.

**Comment by hobbes1069** [comment]
I'm still learning about docker, one thing I've noticed is you have to commit changes, otherwise any changes you make are lost when you exit the container. If you can't do it on the fly, then what happens if you have sudden power failure?

**Comment by flareofghast** [comment]
The issue is, if I recall correctly, if you wish to run mineos on a vps, docker is likely being blocked. I tried to use a docker based program once and my vps provider told me it uses some form of virtualisation or something. 
Whether true or not I couldn't use it with my ram node vps.

**Comment by hobbes1069** [comment]
Ok, I figured out how data persistence works with volumes ;) 

I also played around with the supplied docker file and everything completed except the last step. It couldn't find the package.json file but I ran it out of another directory and pointed to the Dockerfile with the -f option.

**Comment by LarsOL** [comment]
Hey, a friend and I have been playing around with the docker image and have to say it looks great.

Couple small things, 
1.  We spent 20 min trying to figure out why the web ui was not up, only to realise the server is https only. (stupid mistake I know but should be in the guide).

2. The docker process is attached to the npm start, and the node server does not seem very stable. Hence brings down the whole docker container when it crashes. Until it is stable, maybe it should be spawned with a script that starts node then restarts it if it crashes?

3. Since docker containers are meant to be run for a specific propose, it should be set up on a minimalistic base image. e.g alpine linux, and try to eliminate any supporting frameworks that are not directly related to running the app. If I get time ill try to re-do the docker file with this in mind.

Great work, and really impressed with the web ui.

On a side note the node crashes are normally around the spigot processes. Dont know if you want a diffrenet issue for that.

**Comment by KiloJuliet** [comment]
I've been using mineos in a OpenVZ template for a while because docker networking is annoying when you deal with more than just a few instances. A good idea would be to generate scripts that would help set up mineos on any type of container or vm with tweaks for each supported distro/version.

Should we start collecting install procedure notes since they do seem to vary a bit here and there?

**Comment by hexparrot** [comment]
MineOS is now available as Docker images: https://github.com/hexparrot/mineos-docker

These images are production-ready, but lack almost all documentation for those to use who are not already familiar with Docker, soooooo...
