### ISSUE TITLE
can't do anything

### ISSUE THREAD

**Issue by FinlayDaG33k** [hexparrot/mineos-node#165]
I've tried settingup MineOS with the ["installer" script](https://gist.githubusercontent.com/hexparrot/1a7a2881d6c951d693d6/raw/6ea2dc00749fdb81dff001d5256b9b86b1590669/install_mineos-node) but I can't do anything once I'm in the webpanel (can't create profiles as there are no jars showing up, and I can't import my existing server because the .zip is not showing up) I don't think it has to do with the permissions on `/var/games/minecraft` because I already set the permissions on 777 (will be changed once I'm able to use the panel properly)

I'm trying to run this on a Raspberry Pi2

**Comment by hexparrot** [comment]
Based on your symptoms, something is definitely wrong...impossible to tell from just those details though.   My best guess is that something failed to install, perhaps related to the repositories you have available to your system being a RPI2 rather than the very-throughly-tested x86/x64 Ubuntu/Debian repos.

On an RPI, you're likely using ARM Rapsbian repositories.  While MineOS most certainly works on RPI/RPI2, something small could have come up that you did not see by using the installer script (a small error, failed download, etc.).

You might try reinstalling the webui from the beginning (no need to reinstall the OS), as pretty much every command (except the git clone command) should be able to run atop an existing attempt without error.  Maybe this will help the issue preventing the webui from working emerge.
