### ISSUE TITLE
Latest version of MineOS can't seem to tell the server is running.

### ISSUE THREAD

**Issue by ciak2009** [hexparrot/mineos-node#172]
The server is running, and started in a screen, the log even appears in MineOS but the status does not change and remains on down, so any action I take tells me the server must be running first.

If I can provide any more info let me know, hopefully its just something silly and I'm missing it :P

Edit: This doesn't seem to happen with vanilla servers, but does with forge/kcauldron for some reason.

Thanks!

**Comment by ciak2009** [comment]
This may be related to #173 not 100% sure though.

**Comment by hexparrot** [comment]
What can you tell me to help reproduce this error?

**Comment by hexparrot** [comment]
It can't tell if the server is running because you're using spaces in the server name. Spaces can't be handled properly by the screen instance, so MineOS is looking for the screen instance "mc-Realm of Mianite Testing" but the instance that is being created is "mc-Realm"

Spaces == no go in server names.

**Comment by ciak2009** [comment]
> Spaces == no go in server names.

Yup, that did the trick, thanks!
