### ISSUE TITLE
Hey HexParrot, some help please?

### ISSUE THREAD

**Issue by ciak2009** [hexparrot/mineos-node#180]
Hey!

I've just been tasked to put together a VERY large project in NodeJS, but have little experience in JS and even less in Node, you seem to have a decent idea of what you are doing.

I was wondering if you had any good resources you would recommend, I see that you are using Socket.IO I'm trying to decide what framework will pair with Socket.IO best, currently testing Express.JS 4 but its a bit finicky.

Can't wait to hear your thoughts!

Thanks,

Caleb

(Sorry I know this isn't really the place for this sort of thing, if you have some other communication method or are willing to help me get into the Node mindset I'd certainly appreciate any tips, tricks or resources you can recommend!)

**Comment by hexparrot** [comment]
discourse.codeemo.com should be universal enough to field this kind of discussion; by all means, anything I can pitch in to help I'd be happy to.

To give you a quick answer:

As you might have already noticed, I use Express.JS 3.5; the method to pair together socket and express.js 4 I found to be tremendously difficult, especially with my particular requirements in localauth.  That's not to say that it is impossible--it likely is, but the means to do so evaded me for weeks, so I settled on an easier solution with 3.5.  That means that unless you're going the same direction I did with auth, there's a good chance that using 4.0 is still a better choice going forward, but without knowing your actual requirements, I couldn't tell for sure.  For the most part, if its not part of MineOS (within the `package.json`), I honestly probably don't know enough about it to make an educated recommendation.  Socket.io and express.js seems to work nicely for me, though, so that's where my vote goes.  We can go into further detail in the Discourse forums; feel free to tag it uncategorized, Community, or just to mail it directly to my user there.
