### ISSUE TITLE
MineOS Webui crashing browsers

### ISSUE THREAD

**Issue by Technowix** [hexparrot/mineos-node#181]
Hello, first thanks for your amazing panel, managing a server minecraft is amazing with :D
I came into a problem recently, the lastest version crash my browsers (Firefox and chrome).
I think of a memory leak problem, because I have 2 servers, and the one with 3 minecraft servers crash with more speed than the one with "only" two, both produce a lot of logs /etc :s 
If you need any more information, I can send you anything !
This is easy to reproduce, I think.

**Comment by hexparrot** [comment]
Does `/var/log/mineos.log` show anything?

What error shows up when your browser crashes (javascript console, etc)?

**Comment by Technowix** [comment]
Nothings in the logs (I mean no error or somewhat)
The browser only stop, he crash :/ saying nothing.

**Comment by AlexMason** [comment]
I can confirm, the log files produce text so fast it is hard for the servers to render.

**Comment by hexparrot** [comment]
I'll look into a way to perhaps enable/disable logging and tone down the throughput to your browser.

**Comment by AlexMason** [comment]
Maybe add a rate limit to the web UI logger.  such as > 50 msgs a second, it will show no more.

**Comment by hexparrot** [comment]
The problem with a rate-limiter is that a) its programmatically much more complex, but also b) it provides an unreliable log to the user in the webui--it is entirely by luck that logs you want vs logs you don't want get pruned out.

**Comment by AlexMason** [comment]
I am by no means a good programmar, but here is my solution to point A:
pseudo code:
```
(in asynchronous thread)
every 1000ms:
  rateLimitCount = 0

logger method:
  if rateLimitCount < 50
    logger.sendMsg {msg}
    rateLimitCount += 1
  else
    return
```

As far as point B goes, I am not sure how you would go about this, is kind of a trade off I guess.  You could always make it a toggle feature and then leave it up to the user.  Just my input on it.

**Comment by hexparrot** [comment]
I implemented rate-logging today on client-side as you suggested in commit c794f415dad9551387624edb6b9db37f0964a2b6.  This means that the server continues to transmit the logs to the webui (which is potentially still undesirable) but is very simple to implement.  

Once the rate-limit threshold of 50 messages/sec is reached, the webui no longer updates with live updating and adds a notice to the page "The server has been generating logs beyond the rate-limit threshold. Log tailing has stopped and can be re-enabled by refreshing the webui."

This is about as middle-ground as I can think of.  Logs will always be reliable because it's all-or-nothing (and you know when it's nothing) but there still is bandwidth used for data not actually being displayed to the user. I find it a sufficient compromise though, so let me know if this works for your use-case and if 50 messages/sec is actually an ideal threshold.

**Comment by epicminerbackup** [comment]
I don't want to re-open an old post but I'm having issues with this rate-limiting I don't know where I can disable it or what because I'm missing logs that I want to see but I really don't want to go through the hassle of finding the logs in my FTP client (Which makes the down time of my server a good amount long

**Comment by hexparrot** [comment]
You won't want to disable rate-limiting, but you can increase the thresholds as described here: https://discourse.codeemo.com/t/unlimited-log-entries/1533/2?u=hexparrot

That said, if your server is generating logs at that fast a pace, you probably will want to simply view the logs through the terminal, as this is the ONLY way to get the full logs.  In the webui, you only can see log entries produced since the webui was started (and only a small amount going back, if the file is smaller than 256k).

So raising the thresholds is your first goal, but again, if you _need to go through the logs_ then the webui is the least efficient place to do it--and it's incomplete.
