### ISSUE TITLE
Disable "Host Settings" for custom users

### ISSUE THREAD

**Issue by zefie** [hexparrot/mineos-node#184]
I'm looking to allow a few users to control their own servers, but don't want to let them create new ones. Is there a way to disable the entire "Host Settings" section if the user != "root" or "mc"?

(BTW I tried to post on your forum but I cannot sign up because it says the admin has disabled email)

**Comment by hexparrot** [comment]
Alright, so go ahead and switch to the following branch "custom_user".  This should allow you to whitelist users who are allowed to create new servers; only server creation is affected--all other functionality is left untouched.

    cd /usr/games/minecraft
    git fetch
    git checkout origin custom_user
    npm install

And then restart your webui.  Depending on how you installed it, it could be `supervisorctl restart mineos`.

**Comment by zefie** [comment]
`root@mineos /home/mc# cd /usr/games/minecraft/
root@mineos games/minecraft# git fetch
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 4), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/hexparrot/mineos-node
   bcb4bd5..2d22dc1  master     -> origin/master
root@mineos games/minecraft# git checkout origin custom_user
error: pathspec 'custom_user' did not match any file(s) known to git.
`

**Comment by hexparrot** [comment]
My mistake "origin" shouldn't be part of that command.

**Comment by zefie** [comment]
Same error though :(

**Comment by hexparrot** [comment]
Did you restart the server so that the new files are used?

Did you also run the `npm install` command mentioned above? 

Depending on how you installed MineOS, it's likely `supervisorctl restart mineos`

Here's the output I got when using the commands as I gave you--your fetch and checkout commands probably shouldn't look like that.

will@willonubuntu:~/mineos-node$ git fetch
will@willonubuntu:~/mineos-node$ git checkout custom_user
Switched to branch 'custom_user'
Your branch is up-to-date with 'origin/custom_user'.

**Comment by zefie** [comment]
I just removed /usr/games/minecraft and re-cloned it and your original commands worked.

**Comment by hexparrot** [comment]
Has this branch solved your issue?

**Comment by zefie** [comment]
Sorta, yeah. I think it would still be a neat option to remove the entire host section. But I will close this. :)
