### ISSUE TITLE
Bungee console is not interactive

### ISSUE THREAD

**Issue by lasercar** [hexparrot/mineos-node#196]
If I make a spigot server the console works fine, but on a bungee server, I can't type commands into the console.
Running git commit: 5e7c7db
![mineos - bungee console not interactive](https://cloud.githubusercontent.com/assets/6022168/15559712/45c3423c-22aa-11e6-8fd8-5ebbe3fcc50e.png)

**Comment by treyzania** [comment]
I believe this is intentional, as the server is marked as not a "conventional" server.  If you have access to the server over SSH you can still use `screen -x` to attach to it.  (Then `ctrl+A`, `D` to detach.)

**Comment by lasercar** [comment]
Thanks very much! That works good enough for me.

**Comment by hexparrot** [comment]
Just added this feature for an interactive console on the "proxy.log.0" page.  It existed before, but evidently I didn't know enough about bungeecord.

All commands I would type would return: 

```
15:54:49 [INFO] Listening on /0.0.0.0:25577
15:56:23 [INFO] ?cCommand not found
15:56:25 [INFO] ?cCommand not found
15:56:30 [INFO] ?cCommand not found
15:57:29 [INFO] ?cCommand not found
15:57:42 [INFO] ?cCommand not found
```

Turns out that as long as I'm typing in the commands perfectly, no slash, no '?' or 'help', it actually works.  Update 9bc5b3f30010465b2307b5625cfdd82c818d19c3 and it should be there for you.
