### ISSUE TITLE
Sponge profiles

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#200]
The sponge profiles is not good, the last version is not the build # 172 but https://repo.spongepowered.org/maven/org/spongepowered/spongevanilla/?buildTypeId=7

**Comment by lasercar** [comment]
All the versions show up fine for me. Although it is confusing because the newest are on the bottom instead of top, maybe the list should be sorted with newest on top?

**Comment by hexparrot** [comment]
It's ordered alphabetically, since the XML file itself doesn't provide any data about when it was released.  While it could very well be sorted by increasing versions, then some sort of sorting code would have to be implemented, but quite frankly, the cost/benefit of doing that is a little low.

If you can identify any other feeds (rss/xml/etc) that provide metadata such as release date, such as the official mojang feed does: https://launchermeta.mojang.com/mc/game/version_manifest.json, this can be more easily implemented.

**Comment by hexparrot** [comment]
All sponge profiles appear.  If there's one in specific you cannot find, try release type "Show All" and scroll through the list or page-search.

They aren't ordered the preferable way (descending based on age), but they should all be available and working.  Let me know if you have any other issues.
