### ISSUE TITLE
Restore point space usage

### ISSUE THREAD

**Issue by s33d1ing** [hexparrot/mineos-node#209]
After several restore points, the space used by restore points shows as 0B instead of the correct usage.  It appears to happen after more than 1GB of restore points are created.

**Comment by hexparrot** [comment]
Depending on the file counts that are being created by your server, it might be that MineOS isn't able to do get a recursive file size by the set timeout of 3 seconds.

https://github.com/hexparrot/mineos-node/blob/master/mineos.js#L1267

As you can see here, after 3000 ms (3 sec), if the filesystem doesn't report a file size, it defaults to 0.    This timeout is in place in case there is such an egregious file count that it takes too long (and it makes the UI feel entirely unresponsive).

While it's possible to raise this timeout value (in the source), it's not recommended because all the data gets populated at once--if you raised it to 10 seconds, for example, and it took 10 seconds to get the value, you'd also have to wait 10 seconds for other fields to update.

So, you can either reduce your restore points by pruning them out (which you shouldn't feel obligated to do), or use the command line to find out:  `du /var/games/minecraft/servers/[servername]`.
