### ISSUE TITLE
Cronjobs

### ISSUE THREAD

**Issue by drkmachine** [hexparrot/mineos-node#210]
First let me say I love this. Now I installed MineOS-node on a freenas 9.10 machine following the instructions here.

https://forums.freenas.org/index.php?threads/how-to-install-mineos-node-in-a-jail-alternative-to-using-the-mineos-plugin.44686/

All runs well, except I cannot seem to get cron jobs set. I have entered the expression:
* */30 * * * *
and set it to create a new restore point, but when I click on submit cronjob nothing happens. 

I have 2 servers, first one is a vanilla server and it lists 5 cronjobs that I can't seem to do anything with and the second is a forge modded server that shows no cronjobs and won't let me add any.

**Comment by hexparrot** [comment]
The npm package MineOS uses is [cron](https://www.npmjs.com/package/cron) (this is also the page linked to from the webui.

Notice, there is a different expected format from this documentation than what you are using (5 values vs expected 6).

**Comment by drkmachine** [comment]
I'm sorry, typo. The actual expression I am using is:

* */30 * * * *

**Comment by drkmachine** [comment]
Nevermind. It is working. the page has to be reloaded for newly added jobs to show up. Is this normal?

**Comment by hexparrot** [comment]
No, the normal scenario is that everything updates in-place immediately.  However, the MineOS FreeNAS plugin runs into an inordinate amount of technical compatibility issues that makes it run much more poorly (buggy) than any other MineOS installation; the most pertinent issue being that the FreeNAS plugin evidently has troubles using more recent updates.  If I recall correctly, it uses this [old commit](https://github.com/hexparrot/mineos-node/tree/v1.1.2)--which is 119 commits obsolete.

These compatibility issues exist because many updated modules that MineOS depends on in the NPM repository all have been updated for more modern Node versions, which the FreeNAS plugin is also not using.  The plugin is not maintained by me, but by a FreeNAS developer--so these difficulties are pretty much insurmountable if he couldn't get them to work.
