### ISSUE TITLE
Dashboard opens when not logged in

### ISSUE THREAD

**Issue by djoey123** [hexparrot/mineos-node#216]
You can open the dashboard when you are not logged in.

Maybe it is a good idea to redirect when ther is no session to the login page.
http://prntscr.com/cc5ve8

a other thing:
Maybe it is nicer when the show password always is checked as default?
commited a Pull requests for it

**Comment by hexparrot** [comment]
I haven't been able to reproduce this issue.  Each time the session expires (such as restarting the webui or host), upon refresh of the page (because the page otherwise is unchanging), it always brings me to the login page.  

I'm not sure why it's doing it, but it's loading for you the public html that is the webui (but obviously missing any part dynamically filled in).  In short, it's definitely not desirable at any point to show the webui (rather than the login), but it is 100% not exploitable, at least.

**Comment by darkwisperer** [comment]
I have been able to reproduce this on one of my PCs that had never been to the web-ui

**Comment by hexparrot** [comment]
Alright, well unfortunately, in the hundreds/thousands of times I've opened up the webui, I haven't been able to reproduce this behavior.

I'm not saying it's not happening, but if I am unable to reproduce it, I am definitely unable to fix it.  Using chrome (the browser you're using in the screenshot), I went so far as to even type in the URL of the dashboard itself ('/admin/index.html') and it still, consistently redirects me to `/admin/login.html`.

Can you provide any details about your system (what distro, what commit, what browser) that can help me reproduce this?
