### ISSUE TITLE
No username in top right menu, no servers visible

### ISSUE THREAD

**Issue by thisischrys** [hexparrot/mineos-node#224]
Log shows nothing abnormal, just server discovery and autostarting (tried disabling it through the conf file, it still won't show up)
I have recently updated to node7, is it supported?

**Comment by hexparrot** [comment]
mineos-node was built and currently only tested on the Long-Term Support Branch, 4.x.  While there has been largely no issues on 5.x and such, the higher up the version, the more API changes made, the more likely something will fail: in this case, the culprit is most likely in the npm dependencies. 

I assume you rebuild all your npm dependencies (and preferably, deleted .node_modules, first).  Did all of the dependencies build without errors?  If not, please do so and it may illustrate the problem at hand.

**Comment by thisischrys** [comment]
deleting .node_modules/* first did the trick
