### ISSUE TITLE
Be able to view more logs.

### ISSUE THREAD

**Issue by carbotaniuman** [hexparrot/mineos-node#225]
Is it possible for there to be a way to view **every** log in the logs folder? I'm still trouble shooting FTB right now (the FTB jar I'm supposed to start produces no logs in the latest.log file), so i have to manually go into SSH. Is there any way not t o?

**Comment by hexparrot** [comment]
Unfortunately, the webui isn't designed in such a way that it can easily include additional logfiles; each file would require changes to the backend, the front-end, and also would increase the memory footprint.

If you need to constantly check a file for changes, you have options in `tail` via SSH (which really is the best--quickest feedback), or webmin (if you're using the Turnkey ISO).  It might require quite a bit of code rewrite to make it include more logs which isn't likely to happen, I'm sorry to say.

**Comment by clowrym** [comment]
Would be nice to have some type of log rotate, I frequently have "File greater than 256k, only new lines will appear here", especially on my Bungeecord server. Currently I go manually rename, & delete old logs I dont need. Might be nice to have a list of old logs, similar to the list for Back-ups where you can prune old logs & Mine-OS automatically rotates once it reaches max size. Just a thought!!

**Comment by hexparrot** [comment]
I think more modern versions of Minecraft (official, vanilla) and many other 3rd party softwares already do log rotation. 

I definitely wouldn't want to delve into log rotations (my own variant) because that's an undertaking already well-scoped out enough for specialized projects, but even implementing them might be a bit iffy.

I'd say it's likely MineOS could cleanly implement log rotation without it stepping on the toes of existing log rotation that Minecraft servers already implement.

The 256KB limitation is a very arbitrary limitation--mostly because if it happens to be running a version that _doesn't_ log rotate, it seems mostly unnecessary for each instance of the webui through a browser to open the file (on the server-side), use that memory, and then transfer it over to each user.  If you would like that limit raised, you can do so (on an individual basis, to the js code on your server) which could help alleviate the need to drop into the filesystem.

But the long and short of it is: whatever the size is of the log file has to be loaded then transmitted --whether or not the user logged into the webui uses it -- so it seems often a big resource waste.

>  Might be nice to have a list of old logs, similar to the list for Back-ups where you can prune old logs & Mine-OS automatically rotates once it reaches max size.

This is kind of a cool idea though.  I'll continue to look if there's a scaleable way to have more logs added to the webui (right now, each is hardcoded and hidden if absent).

**Comment by diabolicallyrandom** [comment]
I found this when looking around, it could be a good point of reference if nothing else. Additionally it could be a tool that carbotaniuman could use while waiting/hoping for something better / MineOS specific:

https://github.com/NarrativeScience/Log.io

**Comment by hexparrot** [comment]
I just pulled in #246, a PR that addresses having logfiles _not limited to the ones hardcoded in the webui!_

You can see the required change to `/etc/mineos.conf` here: caa79ecb4da42d8c70682b77c1abd14689db8712

An example of this in use would be:
`additional_logfiles = 'log/fml-junk-earlystart.log,server.log'`
with each file comma-separated and relative to the servers' directory itself.

Restarting the webui is a necessity after each update to `mineos.conf`, but otherwise all files should now dynamically be rendered on the webui.

**Comment by clowrym** [comment]
my Ubuntu-vivid won't start after this change for some reason

`2017-06-14 23:09:16,856 CRIT Supervisor running as root (no user in config file)
2017-06-14 23:09:16,856 WARN Included extra file "/etc/supervisor/conf.d/mineos.conf" during parsing
2017-06-14 23:09:16,867 INFO RPC interface 'supervisor' initialized
2017-06-14 23:09:16,867 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-06-14 23:09:16,867 INFO supervisord started with pid 1
2017-06-14 23:09:17,870 INFO spawned: 'mineos' with pid 2702
2017-06-14 23:09:18,407 INFO exited: mineos (exit status 1; not expected)
2017-06-14 23:09:19,410 INFO spawned: 'mineos' with pid 2712
2017-06-14 23:09:19,895 INFO exited: mineos (exit status 1; not expected)
2017-06-14 23:09:21,899 INFO spawned: 'mineos' with pid 2722
2017-06-14 23:09:22,383 INFO exited: mineos (exit status 1; not expected)
2017-06-14 23:09:25,388 INFO spawned: 'mineos' with pid 2732
2017-06-14 23:09:25,388 INFO spawned: 'mineos' with pid 2732
2017-06-14 23:09:25,873 INFO exited: mineos (exit status 1; not expected)
2017-06-14 23:09:26,874 INFO gave up: mineos entered FATAL state, too many start retries too quickly`

I'll try and remove the container and re-add it

**Comment by hexparrot** [comment]
@clowrym this might be unrelated to the log update, but instead related to one of a dozen other commits that have happened recently.  It could also be related to the recent npm module issue that cropped up...I suppose the possibilities are too hard to narrow down.

That said, the log issue I think is resolved, but I'll happily help assist if you want to start a new issue involving the docker issue.  (oh, another thing, I'm no longer maintaining the Ubuntu-vivid image.  There's nothing I can think of that has been done to make it _stop_ working, but I'm no longer hosting it on docker hub--for simplicity.)

**Comment by clowrym** [comment]
Interestingly enough I beleive its something on my end. I can do a clean install on a machine thats never had this docker installed & it will run fine, but on my existing systems, No go. If I cant figure it out, I'll start a nother thread!
