### ISSUE TITLE
Trying to Manage a server with more than one user

### ISSUE THREAD

**Issue by ozhound** [hexparrot/mineos-node#228]
Hi,

As i read it, users belonging to the same group can see and manage the same servers. To that end I have done the following

Initial setup was done using https://minecraft.codeemo.com/mineoswiki/index.php?title=MineOS-node_(apt-get%2Bsystemd) using my own user account (not root, but belongs to the sudo group)

I want to give the user "mc" belonging to the users group access to manage the servers that i have created. So I did the following
Added my user to the users group
Created the mc user in the users group

chown all files in the /var/games/minecraft to mc:users

I actually restarted the physical server at this point due to a system update.

i logged into mineos with mc user and see nothing

i tried reloading supervisorctl. still nothing

i tried chown on all files in /usr/games/minecraft to mc:users, still nothing

I tried creating a new server under mc username but it does nothing. There is something funny going on as the "mc" username doesn't even show on the GUI.

![image](https://cloud.githubusercontent.com/assets/3649237/22587458/b64037fe-ea3c-11e6-8c2f-245cae43c8f3.png)

i tried updating the /etc/supervisor/conf.d/mineos.conf to user=mc from user=root this just stopped mineos from running

I archived the server when logged in as my user, and even though i copied it to ./import and chown it to mc:users it doesnt show when logged in as mc.

is there something else i have to do?

**Comment by hexparrot** [comment]
Can you provide the `/var/log/mineos.log`?  I see the top-right hand is missing the "logged in user" (where it should say `mc`).

Also, how did you create the user, are you able to recall the command?  What I'm interested there is whether or not you created `mc` with a primary group `users` or if its a supplementary one.

**Comment by ozhound** [comment]
@hexparrot sorry for the delay. my log is quite extensive as ive been running mineos since october last year. https://paste.ubuntu.com/23959439/

I created the mc user originally back in october, so i cant remember exactly what i did back then.

**Comment by hexparrot** [comment]
So I think what ended up happening here is that when you created the `mc` user, you gave it just membership to `users` but not to the (conventionally created) `mc` group.  It's usually the cleanest way to go about things when creating users so let's try to mimic that.

Here's what it looks like when I created my `mc` user:

```
root@mineos games/minecraft# id mc
uid=1000(mc) gid=1000(mc) groups=1000(mc)
```

One indication things are set up in a normal way is that `mc`'s home `/home/mc` will be owned by `mc:mc`, which makes sense.  But yours on the other hand, might instead be `/home/mc` owned by `mc:users`, which probably gives members of `users` access to a place they shouldn't.

But the alternative is that maybe you did have `mc:mc` created, but you accidentally just _changed_ the `mc` primary group instead of _adding_ membership to a different group.

At any rate, try this out as root:

```
groupadd mc        //dont type this, just describes:  creating a new group called mc
usermod -g mc mc     //changes the primary group of user mc to group mc
usermod -a -G users // adds group 'users' to mc, making it part of mc (primary) and 'users' (supplementary)
id mc
uid=1000(mc) gid=1000(mc) groups=1000(mc),1002(users)
```

this should look similar to the results above.  The (mc) portions should match and there should be a number for all entries (even if the numbers are different).

**Comment by ozhound** [comment]
Hi Mate,

That worked

It seems that i create the mc user with the primary group as "users" and the mc group didnt even exist. so after creating that and assigning the user mc to the mc group as its primary it now logs in correctly and i can see all the servers belonging to the users group.

Thanks for the assist.

![image](https://cloud.githubusercontent.com/assets/3649237/23014168/d89f7dce-f468-11e6-9115-b171138b7358.png)
