### ISSUE TITLE
Ability to browser server files enable/disable/add/remove mods etc

### ISSUE THREAD

**Issue by xordac** [hexparrot/mineos-node#241]
As the title says, a basic file explorer that defaults to each "server" (minecraft instance) would be great to help manage mods. The same function could be used with the profiles to allow editing or creating new profiles. This would make life a lot easier when trying to manage servers remotely when all you have is a web browser and you dont have an ssh client to do all that you want to do.

**Comment by hexparrot** [comment]
I'd assert that if _all_ you have is a web-browser, it's probably not the ideal time to be doing things such as add/delete files on the file system.  Not that doing these things are inherently dangerous or even difficult, but moreso the idea that this seems to aim toward the idea of mobile-device usability, which...MineOS is unlikely to be able to tackle.

Web-based file explorers are not small tasks, so the options are either to a) design one or b) implement an existing one.  'a' seems obviously unlikely--the codebase and manpower requirement for such a thing is monumental (especially when you consider the consequences of bugs and responsive UI). 

'b', however, seems equally as unlikely.  If I were to find an existing file explorer, it 1) wouldn't match the webui, stylistically and 2) may or may not use the appropriate backend and auth.

So, consider options like Ajaxplorer and Extplorer.  Both are very hugely polished file explorers, that 1) do not match the webui stylistically and 2) require a backend like Apache (or at least that's what's documented, vs. nodejs custom projects).

So the next question is: does it need to be integrated at all?  MineOS Turnkey offers a web-based file explorer through Webmin; again, no style match and a completely separate, non-integrated functionality.  It is disabled (but present) in MineOS Turnkey installs and has mixed reviews.

Now the most pertinent question: is integration important?  Or is it simply web-based access?  Because if it's the latter, you can give yourself easy access to files (upload/delete) via existing mechanisms (albeit installed manually).  But despite being installed manually, it also means it doesn't greatly complicate the existing MineOS setup for those who opt to use SSH or SFTP clients (like filezilla) to already efficiently manage files, both on desktops and mobile.

So, personally, I believe life would be made a lot easier to depend on these polished, commercially maintained apps (like filezilla) rather than to increasingly add functionality to MineOS that would be a shoddier implementation.

**Comment by diabolicallyrandom** [comment]
I concur that integrating file browser and management functionality beyond the simplistic nature of the capacity to copy profiles and manage archives and backups that already exists is going a bit beyond the scope of what one should be looking for in the mineos webui. It seems like having a separate control panel of some kind that isn't integrated if this functionality is absolutely necessary would be both cleaner, and easier. There are tons of such solutions already out there that can be easily installed on various platforms.

Additionally, it seems like it would open up a lot of potential for unintended security holes, and puts a lot more on the shoulders of what is mostly just hexparrot currently.

**Comment by xordac** [comment]
I already run webmin on pretty much all my game servers, hard to live without it. I figured there was no harm in asking since I think managing forge mods or bukkit plugins is something I thought would be common among server admins. I saw the feature is part of 2 other MC server admin solutions that shall remain nameless.
