### ISSUE TITLE
rdiff-backup --list-increment-sizes running when it should not?

### ISSUE THREAD

**Issue by 4o66** [hexparrot/mineos-node#245]
While using the server archive page to prune older archive files, top is showing me "rdiff-backup --list-increment-sizes" running as well, multiple times.

Additionally, changing back and forth from the backup page can spawn multiple copies of the command. This can spike demand on the cpu and i/o subsystem if there are many rdiff points.

Is this being called where it should not?

**Comment by hexparrot** [comment]
In order to ensure accurate information, almost all **commands** received by the webui, e.g., archive, backup, prune, etc. will invoke a refresh, which includes --list-increment-sizes.

Changing between pages should not invoke a new check (it's merely a client-side effect).

That said, if the --list-increment-sizes takes a non-trivial amount of time, it's perfectly understandable that _too_ many of these are running and with little to no benefit to the user experience.

I'll look further into this.  I know of ways in which the results can be cached easily, but I have to figure out what's the best way to determine when that cached result is, in fact, out-of-date, and a new check should be made.   Examining....

**Comment by 4o66** [comment]
My main server has 174 increments (1 per hour, 24 hours a day), and I clean it up every month or so.

**Comment by hexparrot** [comment]
Alright, I made a commit that addresses this: 55604b584db46ec4064ec71c8aabb009882a9709

It adds a hard 10-second check for whether or not to get updated information about the number of increments.  I may tune this up in the future (or come up with a way for it to be user-editable ...outside of changing code) as necessary, but in the meantime this should greatly reduce overlapping workloads and also feel mostly responsive.

This change means that there's a short window when it's possible that the list-increments values (and restore points page) are out of sync.  That is, if you did something to the effect of:

1. do any action that invokes a webui command
2. make a backup
3. do absolutely nothing else within 10 seconds of performing # 1 and then
4. wonder why it doesn't appear that the backup was made.

The answer to this is then: 

5. do anything in the webui; refresh it.  start or stop a server, change a dropdown or text value. push any button.

And then everything will resync.  Also, by design, if you have done no commands within 10 seconds and make a backup, it will refresh/resync immediately.  There is going to be a very tiny subset of people who might ever notice the number not incrementing--I'm not sure it'll ever be big enough a deal to make a complaint/github issue because they can literally do anything after 10 seconds and it'll come back to normal.

That said, it should guarantee that you never have --list-increments running more than once per 10 seconds, and if it finishes within 10 seconds, then this is a 100% fix for you.
