### ISSUE TITLE
Webui takes really long to load on bad internet connect

### ISSUE THREAD

**Issue by MWFIAE** [hexparrot/mineos-node#260]
The webui takes really long to load for me. 

I managed to speed it up by enabling compression.

http://blog.fossasia.org/using-compression-middleware-in-nodeexpress/

But I know that 2 lines of code made it alot faster for me and can't destroy anything for others either, so please add it in :)

```
var compression = require('compression');

app.use(compression());
```
before the other app.use calls in webui.js

**Comment by MWFIAE** [comment]
@hexparrot 
What do you say?

**Comment by hexparrot** [comment]
It's a good npm module; I've added it in commit d529e7097a619848e7f0205313a025e053481166.  

I'm always wary to make changes like these when they require new `npm` modules because of the apparent increase in people who update the webui, but without following all the steps (including `npm install`).  This inflates the number of people who say "the most recent commit broke my webui!" even if its because there's a simple step _they should've known to do_.

That said, I couldn't let that cripple a good improvement, so here it is.  Now I'll have to also update the ISO lol.

**Comment by MWFIAE** [comment]
thank you! :)
Performance (and therefore usability) improved extremly for me after I added it in, good to know that other users could profit as well 👍 

Maybe you could use githooks to automate the npm install, I never used something like that (or pretty much any git feature besides basics checkouts and commits), so I'm not sure how to do it. But I found the documentation for it:
https://www.kernel.org/pub/software/scm/git/docs/githooks.html
