### ISSUE TITLE
noticed a couple of issues

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#273]
Howdy, long time.
I setup a VM for the kids tonight and came across a couple of things.
I tried to install using Node 8.11... I couldn't get it to work so am running it with the latest from the source listed in the readme, 6.X. This seems to work.
1) interestingly npm module USERID wasn't being loaded or something using npm install, had to manually install using npm install userid?? it's listed in package.json and showed that it had installed so not sure whats going on there.
2) readme is missing a step to 'cp mineos.conf /etc/mineos.conf'

**Comment by supra63200** [comment]
I just had the same issue. After an upgrade, mineos just stopped working. I checked the logs and it was missing the USERID module, which I had to reinstall manually.

**Comment by hexparrot** [comment]
Thanks!  I was able to easily fix #2, but the #1 USERID module not loading/installing is... bizarre.

I definitely have heard of this issue before (that is, I've heard reports and tried to get a repro case), but it made as little sense to me then as it does now!  It's clearly in the `package.json`, so I'm not sure why there's any instance where `npm` decidedly doesn't use or build it, despite it being told to.

I wonder if it's related to the node version.  Presumably the modules themselves (at least at the versions I incorporate) would need to be updated for a newer Node (I chose 4.x because it was LTS), but maybe I can check the full spectrum of node versions to see what USERID version will work across the board (if this is the issue).

**Comment by hexparrot** [comment]
If this issue persists, please let me know--I'd love to be able to reproduce it and find a fix for all future users.

As of right now, I've been finding great success on CentOS/Ubu/Deb that 8.11 is building USERID as expected.  Don't hesitate to reopen this issue if you feel it has not been sufficiently addressed.
