### ISSUE TITLE
1.12.2 Latest.log display issues

### ISSUE THREAD

**Issue by marckskl** [hexparrot/mineos-node#274]
This has just started happening recently to me. On my 1.7.10 servers, Latest.log displays normally, [![Screenshot from Gyazo](https://gyazo.com/c28c3403a683810c21a19909f545c4e3/raw)](https://gyazo.com/c28c3403a683810c21a19909f545c4e3). 
On my 1.12.2 instances, they show up with &r after most things and also seems to display the "net.minecraft.server....." things too [![Screenshot from Gyazo](https://gyazo.com/fb94949259a99b6138c60b85f0109099/raw)](https://gyazo.com/fb94949259a99b6138c60b85f0109099) I have a 1.12.2 instance on forge 14.23.0.2512 and it doesn't do that to the logs. The one that is having issues is on forge 14.23.2.2651 so it makes me believe its a Forge change in how they display the logs. Is this anything you can look into?

**Comment by hexparrot** [comment]
I'm not sure how we might address this change in code in any meaningful way, really.  The webui does a very naive load of the server logs themselves; (that is, the service daemon just reads the file and sends it to the browser).

The problem is that I can't seem to have any user-specified values sent to the browser (webui) for what we would want to remove.  I wrote some code to prune out text based on a regex, but I ran into the problem where a) it was either hard-coded into the JS or b) I had to modify the server to send the new mineos.conf value I created to hold the regex.

The latter had me changing code in all sorts of places, and I started getting pretty worried that that was a lot of places where it could mess up the webui and necessitated a lot more error checking, and it started feeling really bloated for the niche purpose.

I'll have to do more pondering, but in the meantime, I'm afraid I have nothing to report in terms of how to address the extra spam.
