### ISSUE TITLE
Add NPM to apt-get line

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#276]
I got a message that NPM wasn't installed when trying to run NPM install.

apt-get install npm worked.

seems like this is not installed with nodejs.

**Comment by hexparrot** [comment]
How did you install Nodejs?   If you installed it through the means provided in the installation instructions, e.g., `curl -sL https://deb.nodesource.com/setup_4.x | bash -`,  `npm` should be included in that install.

If you installed nodejs without that line (e.g., not using the Argon LTS repository from above), then yes, `npm` would be separate.

I kept these as separate lines because it was to encourage use of the LTS version 4.x (now 4.9) since there would be a number of rewrites and code adjustments required for newer node APIs.

**Comment by flareofghast** [comment]
Actually in the readme it says - on line 3 
apt-get install nodejs...

**Comment by hexparrot** [comment]
Okay, well I have no idea what distro you're using or whether you checked if there was any errors when you did run line 1.

`apt-get install nodejs` on its own installs the distro's Nodejs, comes without NPM.
That curl line adds the Argon LTS repository.  NodeJS comes with NPM in every install I've ever done so far.

I don't know what to say.

**Comment by hexparrot** [comment]
I've updated MineOS-node to now use Node v8.  This LTS support line (as opposed to 10x, etc.) seems to be pretty API-compatible with the existing codebase. 

That said, I still expect `npm` to be installed with *just* nodejs, as I see in this output from the line 1:

```## Run `sudo apt-get install -y nodejs` to install Node.js 8.x LTS Carbon and npm```

If you run into any other behavior where it's not installing `npm`, let me know what versions of whatever it is you're using and I'll try to reproduce.
