### ISSUE TITLE
update_webui.sh failes on latest version of Node on FreeBSD 11.2

### ISSUE THREAD

**Issue by Sykout** [hexparrot/mineos-node#318]
I was doing a bunch of updating in my FreeNAS mineos jail when I encounter this problem

Poking around, I think node-gyp is having trouble compiling the npm package "posix" under the node v12. This is on the latest commit SHA d743d2236d27781e36202d0524435383d9787b71

I ended up having to rollback my node10.16.3/npm6.11.3, and it works fine there.

This is more of a surprise as it does not seem to be documented anywhere.

Attached is the Debug log from NPM when this errored out
[2019-12-12T13_04_52_815Z-debug.log](https://github.com/hexparrot/mineos-node/files/3956096/2019-12-12T13_04_52_815Z-debug.log)

**Comment by hexparrot** [comment]
All the code that I've written that constitutes the webui and the backend is code that generally will run on any nodeJS version.

However, to save myself an immense amount of time and effort reinventing the wheel, I've opted to use many of the available libraries Node has to offer, such as `posix`.

The developers of `[posix](https://www.npmjs.com/package/posix)`, however, are not currently maintaining the module to keep up with the advancements in NodeJS versions, which is why you're experiencing this build issue with v12.

If `posix` is updated to build on v12 on FreeBSD, then you could have expected this to work.

> This is more of a surprise as it does not seem to be documented anywhere.

It's hard for me to keep up by pre-empting all new versions of node and actively reporting what versions don't work, which is why in the wiki, I simply direct all users to download Node8--a known-working version.

**Comment by hexparrot** [comment]
Node v10 is officially the Node I prescribe in installation instructions now, but it appears it might only be a matter of time before v10 EOLs (2021-04-30).

Hopefully then either the `posix` author will update it for compatibility or I'll move on to a newer iteration.
