### ISSUE TITLE
When new profile is created there is no option to choose profile

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#32]
so I have to create the server then change the profile from the default 1.7.9 to whatever I want.

**Comment by flareofghast** [comment]
And server is not assigned to runnable jar

**Comment by flareofghast** [comment]
And with ftb infinity at the least it doesn't actually start, even after accepting the eula.

**Comment by hexparrot** [comment]
For infinity, that requires the minecraft_server.1.7.10.jar.  Unfortunately, even if one were to run the java jar from the command line manually, they would be greeted with unintelligible errors.

Unlike almost all of the other packs, this one requires the ServerStart.sh...which I'm thinking about having added to the dropdown, but it's starting to get pretty yucky at that part, as the startup scripts are often flooded with awful hard-coded values, java arguments, and paths I would be afraid to trust *blindly*, e.g.,   user just opts to run a script, because it's there.

**Comment by hexparrot** [comment]
The 1.7.9 default is actually just so my test suite works.  Eventually I intend for there to be *no* default, and a notice that pops up (like a modal window) that presents all the essential startup values that should be reviewed before start, e.g., profile, runnable jar, XMX.

**Comment by hexparrot** [comment]
This modal window has been designed and implemented into the master branch, and I think it's pretty good at helping users get through the initial setup.

**Comment by hexparrot** [comment]
I think this has been fixed over the numerous commits that tangentially affected creation and detection of profiles.  If the issue persists, please do reopen.
