### ISSUE TITLE
FTB - at least infinity

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#33]
With the FTB packs, to truely make it "idiot proof" we'd need 
```
if (exists install.sh){
  read $JARFILE from install.sh
  download (or link to) $JARFILE (as ./minecraft_server.${MCVER}.jar)
  download (or link to) $LAUNCHWRAPPER (as libraries/${LAUNCHWRAPPER})
}
```

I hope you can figure out for yourself what that all means :smile:

**Comment by flareofghast** [comment]
It looks like it is required to use SeverStart.sh. I manually accepted the EULA and started the server with MineOS, I think the JAR checks to see if it was started by ServerStart.sh, if it is not it changes the eula back to false.

**Comment by kalvindukes** [comment]
I'm hosting an infinity server with the phyton implementation of MineOS and I've never run into such a thing. 
From what I understand, this doesn't use ServerStart.sh either. 



Von unterwegs aus gesendet.

**Comment by flareofghast** [comment]
Is it the latest FTB? 
Are you using any command line arguments?

**Comment by kalvindukes** [comment]
It's v1.3.4. which is not the last recommended release (1.4.1) but this recommendation was just changed from 1.1.0 to 1.4.1 about two weeks ago. 

I'm using a VM switch, which seems to speed up chunk generation significantly as well as XX:PermSize

But that gets injected by the Java Args-Field of MineOS

I'll try and upgrade the server in the next weeks but I'll have to check in with my users first. 

> Am 06.05.2015 um 08:55 schrieb Peter Salzmann <notifications@github.com>:
> 
> Is it the latest FTB? 
> Are you using any command line arguments?
>

**Comment by flareofghast** [comment]
Can you give me exactly what arguments you're using please. I'll try the jar file execution using them and see what happens.

**Comment by kalvindukes** [comment]
So what I used is -Dforge.forceNoStencil=true  -XX:PermSize=2048m

**Comment by hexparrot** [comment]
I've had no issue creating an infnity server 1.4.1 using the following instructions:

1. Create a new server
2. Download profile 1.7.10 and FTBInfinity-1.4.1
3. Go to server-at-a-glance, n
4. select profile "mojang/1.7.10" 
5. Press button "Copy profile to live server directory"
6. select profile "ftb/FTBInfinity-1.4.1"
7. select runnable jar "ftbserver-1.7.10-1352.jar"
8. press button "start"
9. on modal window, ACCEPT EULA, kill server
10. start server

**Comment by kalvindukes** [comment]
That sounds great. Unfortunately I still didn't manage to free enough time and clone MineOS-Node into a new VM to start running tests on my own. :(

@hexparrot sorry for asking again, but did you receive my mails yesterday? :)

**Comment by hexparrot** [comment]
@kalvindukes responded to each email just now.

**Comment by kalvindukes** [comment]
Great, thank you! 
Working with you guys is just enlightening. :)

**Comment by flareofghast** [comment]
@hexparrot did you leave it long enough to check the console that it's loaded and accepting connections. Or, did you play it a bit?

**Comment by hexparrot** [comment]
Apparently I didn't play it enough; it eventually crashes.

It seems to be--as the issue title suggests--just FTBInfinity.  I don't have much (or any) experience running this server pack, so I'll probably have to shelve this issue until later.  I intend to be able to let the web-ui execute Installer shell scripts (but not server starting shell scripts).

I make the distinction because a server start script won't ever be accessible from MineOS because it doesn't start the screen session, while installer scripts are run-once-and-done.

That said, I have faith that the server itself doesn't self-reflect on whether it was invoked by a given shell script by name... one, that means it would break if somebody simply *renamed* the script (which would be awful, pointless design) or it just requires some of those additional arguments (which can be easily added to the web-ui's functionality soon).

If it really requires the shell script by name, I'd officially give up on making it work, but provided it's the alternative, I have every intention of getting a good, noob-friendly workflow, even if I have to put if off for a week or two.

**Comment by flareofghast** [comment]
You can use screen on the ServerStart.sh, or we could look into injecting screen into it.

**Comment by hexparrot** [comment]
Starting the script with screen won't work, since the xmx and xms values are hard coded into the startup script. Also, the way in which Java is invoked by screen specifically is how MineOS can identify the screen process AND the child Java process, which is important: screen instances running Java jars would be identifiable but their children wouldn't be distinguishable from each other. 

At any rate, I'm confident we'll get it figured out in a clean workflow; I'll just need to add a few more interior functions for containing and executing scripts like these.

**Comment by flareofghast** [comment]
I’m going to do a bit more testing when I get the time to see if it can run without the script. If I get it working I’ll let you know. Interestingly when running the JAR at the moment it’s like it deletes and recreates the eula, and install and start scripts. I tried setting 0444 on eula but didn’t stop it changing the eula. Maybe if I change the owner?

**Comment by hexparrot** [comment]
The same steps from my first post appear to work now, miraculously, without any changes.  Perhaps something it downloaded from the internet has since changed and resolved the original issue.  If you find this issue persists, feel free to reopen this issue and include any details of how I might reproduce any errors.
