### ISSUE TITLE
Server that does not create

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#54]
I'm creating a server under test name and nothing happens, the server does not start and when I deconect reconect me and no server n has been create (I use ubuntu 14.04)

**Comment by hexparrot** [comment]
What commit are you using?  What does /var/log/mineos.log say?

**Comment by MrBretze** [comment]
No mineos.log and y using the last commit

**Comment by MrBretze** [comment]
(this commit https://github.com/hexparrot/mineos-node/tree/d6efbb8f29b9fe4b5afa76d7944cb41e93ba72b3)

**Comment by flareofghast** [comment]
I have recreated this with the most recent commit. I have just installed a clean ubuntu 14.04.2 server and found when I created a new server profile as test it did not show up in the UI. The directory and server.profile and server.config and cron.config are created, the directory has 
````
elpres@ubuntu:/var/games/minecraft/servers/test$ ls -la
total 16
drwxrwxrwx 2 elpres elpres 4096 Jun 28 23:28 .
drwxrwxrwx 3 root   root   4096 Jun 28 23:28 ..
-rw-rw-rw- 1 elpres elpres    0 Jun 28 23:28 cron.config
-rw-rw-rw- 1 elpres elpres   44 Jun 28 23:28 server.config
-rw-rw-rw- 1 elpres elpres  207 Jun 28 23:28 server.properties
````

i did a 
````
sudo mineos restart 

````
which now has it showing up. 
Maybe after install a reboot is in order. Will go an check it out now.

**Comment by flareofghast** [comment]
unfortunately I had reinstalled Centos 7 before I tested this, but I can confirm that on Centos 7 it has the same issue. I am just doing a clean install now to see if a reboot on completion fixes the issue.

**Comment by flareofghast** [comment]
Nope. reboot before doing anything doesn't solve it. Maybe it has to do with downloading a profile then going to create a server?
a restart of the service fixes it.

**Comment by flareofghast** [comment]
seems it is just that first profile created, once that is done, then you restart the mineos service and it seems to work hunky dory.

**Comment by hexparrot** [comment]
I'm looking into this now.  On my slow machine, I found that creating servers always create fine but have an unreasonably long delay before showing up in the web-ui, even though they do--eventually--without restarting the service.

**Comment by hexparrot** [comment]
I fixed this just now in commit 450d39a5ce3fd17f6a8226322abd87cb95878ae6.  Turns out the issue is that the file-creation tracker doesn't work if /var/games/minecraft/servers doesn't already exist as a path.  The webui now makes this on first run so this should be completely resolved.

**Comment by hexparrot** [comment]
When updating, do:

git fetch
git reset --hard origin/master
npm install --all

**Comment by kaimi** [comment]
> git fetch
> git reset --hard origin/master

That’s … harsh. Why not just recommend to do a `git pull`?

**Comment by hexparrot** [comment]
It's harsh?  In what way?

I'm recommending a git reset rather than a git pull because of the high frequency of people editing files in the source tree, not knowing that--uncommitted--it will cause an error that will definitely cause confusion.

<pre>git pull
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/hexparrot/mineos-node
   450d39a..354cf0f  master     -> origin/master
Updating 450d39a..354cf0f
error: Your local changes to the following files would be overwritten by merge:
        html/js/scriptin.js
Please, commit your changes or stash them before you can merge.
Aborting
</pre>

I have long accepted that the demographic of MineOS users are not git experts: more often than not, they do not make intentional changes, and they do not make PRs.  When they inevitably edit files in the source tree like this [first edit of this post](http://discourse.codeemo.com/t/how-to-install-mineos-node-on-centos-7-server/591), problems could arise with simply `git pull`, where `git reset --hard origin/master` solves this.:

    sudo sed -i -- 's/nodejs/node/g' /usr/games/minecraft/init/systemd_conf
    sudo cp /usr/games/minecraft/init/systemd_conf /etc/systemd/system/mineos.service

**Comment by MrBretze** [comment]
@hexparrot how to stop the webui ?

**Comment by flareofghast** [comment]
are you running it manually or automatically and on which linux distro?

**Comment by MrBretze** [comment]
i start the webui by this nodejs webui.js

**Comment by flareofghast** [comment]
press ctrl-c

**Comment by MrBretze** [comment]
It does not work

**Comment by kaimi** [comment]
> I have long accepted that the demographic of MineOS users are not git experts

I could write a short guide about making custom changes, making them persistent using branches and updating customised installs. If you’re interested.

**Comment by hexparrot** [comment]
@kaimi by all means!  There may not be many takers thus far on making persistent changes, but it'd be invaluable for those on the fence to know they have a good guide to follow.
