### ISSUE TITLE
Server.Properties

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#60]
Please add more configuration option in the server.properties http://puu.sh/iHGwb/30464c6a31.png

**Comment by hexparrot** [comment]
The server.properties in the web-ui reflect the server.properties actual file.  When you start the server, many of those properties are added to the file itself, and thus appear in the web-ui.

The properties that show up by *default* are those that need to be set before the server runs for the first time, or are super common.  `allow-flight`, for example, you can either manually add or wait for it to appear after your first start.

**Comment by MrBretze** [comment]
the Server.Properties is not auto updated, i log off and reconnect to view the all option (after starting server)

**Comment by hexparrot** [comment]
Ok, have reproduced this bug.  Seems it was introduced recently with my switch from npm module `chokidar` to `fireworm`

**Comment by hexparrot** [comment]
I think I may have fixed this with https://github.com/hexparrot/mineos-node/commit/5f5d9f3847d96256488cfc6620755da0ee5fb8b9, update your scripts and see if the auto-update works!

**Comment by flareofghast** [comment]
Maybe you should have an update button in the UI again? It could run hit reset --hard and git pull.

**Comment by hexparrot** [comment]
@flareofghast the problem is that there might also be changes to NPM's package.json dependencies, wherein updating the web-ui and restarting it would then fail because of npm install --all not being run.

Since it's a multistep process, I can't just have git update (even if it were programmatically done with a git module).  And if I were to add a button, it'd have to do both, which is a sketchy process at best; the reason being that I also have to then include new modules to check for file changes and restart the service (e.g., npm "forever"), and then it just snowballs.

I'm looking right now into just creating a bash script, e.g., update.sh, that will take care of both of these.  I like the idea of using "forever" but then that also requires me to change my service.js script and it's been pretty hairy.  At this moment, and until I can get a better grasp on all the components I'd need to update, I'm just going to recommend manual updates.  Hopefully soon I can implement something nice to automate this.
