### ISSUE TITLE
Imports aren't working

### ISSUE THREAD

**Issue by gh0st19** [hexparrot/mineos-node#61]
Running Ubuntu server 14.04 -2 with the latest git updates. When I go to import an archive it appears to work but never shows the server properties populate or allow me to choose which jar to run. If I restart the process or reload the panel the server import completely disappears.  All of the files successfully extract into the server folder but the server won't show in the panel.

**Comment by hexparrot** [comment]
What sort of file is it?  Where did it originate--MineOS or self made?

Is the file of a reasonable enough size to share so that I can work with a file that actually causes the issue we're trying to solve? (All the zips and tar.gzs I have here all worked, so a non-working copy is ideal).

**Comment by gh0st19** [comment]
It's a tar.gz I made a backup in original MineOS to try on the node version. It's about 1gb but I'm uploading to my dropbox now so should be done in roughly 1/2 hour then I can send you the link.

**Comment by gh0st19** [comment]
@hexparrot I emailed you the link to the file download

**Comment by hexparrot** [comment]
Looks like this is related to: https://github.com/hexparrot/mineos-node/issues/35

Basically, the group from your system, GID 1001 doesn't exist on the new system, and that's crashing it.

Looking into it now..

**Comment by hexparrot** [comment]
Alright, looks like I got this working with the latest commit: 1c768125cd0cd438c78b07c5a170a58b0cda2d12

Successfully was able to import your exact server file.

**Comment by flareofghast** [comment]
What was up with the tar and skin modules that prevented this from working?

**Comment by hexparrot** [comment]
The 'tar' module doesn't re-chown any files after extraction; it expects you to chown it as a separate step, afterward.

However, the server detection mechanism just waits for the directory and server.properties to appear, it doesn't know when--or care when--the rest of the files are extracted.  However, since chowning has to happen *after* the extraction, the detection mechanism sees files that are owned by potentially absent UID/GIDs, and that caused the error.

Specifically, the server file emailed to me was tarred with uid/gid 1001:1001 (tar saves this information).  On a new server, 1001 may not exist yet.  Using the actual tar binary gives the option to extract the file immediately with the correct permissions, thus problem solved.
