### ISSUE TITLE
Task not sheduled

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#74]
Task not sheduled: http://puu.sh/iTjjq/55532e84d8.jpg
Log: https://gist.github.com/MrBretze/3e82b41444f4d6fbecfb

My scheduled task works with a "say Test"

**Comment by hexparrot** [comment]
Do you know for a fact that that exact command works if you were to enter it directly into the console?

**Comment by MrBretze** [comment]
I do not understand what you ask me

**Comment by hexparrot** [comment]
do you know that command would work in minecraft to begin with?

**Comment by MrBretze** [comment]
Yes the command runs in vanilla

**Comment by hexparrot** [comment]
Ok, test that exact command then in the live server console (under logging panel, logs/latest.log).  The input there goes directly into the screen console.

If it works, then the problem is that your command is being broken by it being saved as a cron job.  It might be that all those quotation marks and other special characters are messing it up as its being saved to disk.  We'll know if it works in that panel.

**Comment by MrBretze** [comment]
This does not work in the Logs / Latest.Log

**Comment by MrBretze** [comment]
This is fixed
