### ISSUE TITLE
Cuberite support

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#88]
Suport cuberite in the profile ?

**Comment by hexparrot** [comment]
Support included tentatively through the qbrite branch:

https://github.com/hexparrot/mineos-node/tree/qbrite

Because of design decisions on behalf of cuberite, it is not simple to get the normal console as you do with other server software, so the "Cuberite Console" page is bare and feels half-baked.  This is because the logs are named `LOG_1446756006.txt` rather than `latest.log` or something more dependable.

Not going to pull this into the master branch just yet till these things are worked out, but hopefully soon.

**Comment by MrBretze** [comment]
This version is stable ?

**Comment by hexparrot** [comment]
Stable, yes.  Convenient to read the console? no.

**Comment by MrBretze** [comment]
dont work for me :/ http://puu.sh/lhYjF/f00ba2ff34.png

**Comment by hexparrot** [comment]
That's an OS issue, so you'll have to install the necessary dependencies, presumably through `apt-get`.

**Comment by MrBretze** [comment]
I use openSUSE not debian/ubuntu and zypper has already installed the GLIBCXX

**Comment by hexparrot** [comment]
MineOS is a front-end for Minecraft; it only attempts to execute the binary--if the binary can't be run from the command line, it can't be run from MineOS.  Have you googled the error for an OpenSUSE solution?

**Comment by MrBretze** [comment]
Yes i googled for this error

**Comment by hexparrot** [comment]
and what did you find?
