### ISSUE TITLE
Custom profile

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#97]
Option to create a custom profile (same of mineos py)

**Comment by flareofghast** [comment]
Apparently you don't need to, just stick the jar file in the server directory and choose it.

**Comment by MrBretze** [comment]
Yes, the problem is that you upload our jar and not just select

**Comment by flareofghast** [comment]
I don’t believe William was going to hold hands for every function that needs to take place, such as uploading Jars.
You could fork it and add that functionality if you desire. Unless William says otherwise.

**Comment by hexparrot** [comment]
It's impossible to emphasize enough how much email I'd gotten through the life of the Python webui relating to confusion regarding creating profiles (or in general, how they worked).

While Profiles was eventually something people eventually just "got", I'm sure there are countless numbers of people who downloaded MineOS TKL and stopped pretty much the moment they couldn't import a server without making sense out of a profile--or learning what an "unmanaged" profile is.

With the new design of profiles in mineos-node, admittedly it feels like it's functionality *taken away* from the admin--being able to do it all from the webui (when you understand it) seems like going backward.

But mineos-node has to work for everybody, not just those with previous experience in the webui. 

The mineos-node profile system now is in that sense, less feature-filled, but I would say inexplicably more straightforward.  Now, if somebody imports a server, they really only need to understand one thing: "runnable jar."

So, needless to say, because of how I designed profiles to be always-current and from official sources, such as Mojang, or FTB feeds, etc., it is almost an impossible task to make custom profiles work in the way that it did before.  There would be other ways to get the functionality you care about though:

1. add in functionality that mimics the directory-copying you're used to, e.g., making manual directories and then just having those in the profile dropdown (this still uses non-webui elements though)
2. add in functionality for uploading from the webui

But in all likelihood, 'creating a profile' is probably just an outmoded concept.  Whatever you're trying to do probably either can be done in a nice, clean way already--OR--if it's not good enough, in a way that is different than creating and maintaining some separate registry, e.g., `profiles.config`, worrying about permissions and parsing errors.

Hopefully some food for thought.
